### 文档：vscode-REST Client测试接口.md  http://note.youdao.com/noteshare?id=421cf66f4b6cf4f5fad7314c0d78e059&sub=155723CC56E04B6A8B18BB4FC09A352F
@url= http://127.0.0.1:3000/api
###
POST {{url}}/login
Content-Type: application/json;charset=utf-8

{
  "username": "76871",
  "password": "123"
}

### 获取所有用户
GET {{url}}/user
